name: 'Render and build OpenSCAD project'
description: 'OpenSCAD renderer and builder on github actions'
author: 'flat35hd99'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  scad_file:
    description: 'Input file'
    required: true
  output_file:
    description: 'Output specified file'
    required: true
    default: 'stl'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.scad_file }}
    - ${{ inputs.output_file }}
